services:
  cosmos-prod:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    image: cosmos-prod:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  cosmos-dev:
    command:
      [
        "jupyter",
        "lab",
        "--port=8888",
        "--no-browser",
        "--ip=0.0.0.0",
        "--FileCheckpoints.checkpoint_dir=/tmp",
        "--FileContentsManager.delete_to_trash=False",
      ]
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /app/.venv
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    image: cosmos-dev:latest
    develop:
      # Create a `watch` configuration to update the appl
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./docker-compose.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
